DROP TABLE IF EXISTS personal_data;

CREATE TABLE personal_data ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    dayOfBirth TEXT NOT NULL,
    email TEXT NOT NULL
);

DROP TABLE IF EXISTS work_experience;

CREATE TABLE work_experience ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    fromTill TEXT NOT NULL,
    city TEXT NOT NULL,
    company TEXT NOT NULL
);

DROP TABLE IF EXISTS skills;

CREATE TABLE skills ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    years INTEGER NOT NULL
);